---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: blog-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: blog-repo
  filterTags:
    pattern: "^sha-[a-f0-9]{7}$"
  policy:
    alphabetical:
      order: desc
