apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: blog-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: blog-repo
  filterTags:
    pattern: "^sha-"
    extract: "$1"
  policy:
    alphabetical:
      order: desc
