---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: blog-repo
  namespace: flux-system
spec:
  image: ghcr.io/tur-pve/rblog
  interval: 5m0s
  secretRef:
    name: ghcr-auth
