apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flux-receiver
  namespace: flux-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: flux.api.r2b001.site
    http:
      paths:
      - path: /hook/
        pathType: Prefix
        backend:
          service:
            name: notification-controller
            port:
              number: 80
