---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-release-glasskube
  namespace: flux-system
spec:
  chart:
    spec:
      chart: glasskube-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: glasskube-operator
      version: 0.12.2
  interval: 10s
  targetNamespace: glasskube-operator
  values:
    cert-manager:
      enabled: false
      installCRDs: true
    cloudnative-pg:
      enabled: false
    kube-prometheus-stack:
      enabled: false
      grafana:
        ingress:
          enabled: true
        persistence:
          enabled: true
          size: 10Gi
      prometheus:
        prometheusSpec:
          podMonitorSelectorNilUsesHelmValues: false
          probeSelectorNilUsesHelmValues: false
          retention: 30d
          ruleSelectorNilUsesHelmValues: false
          serviceMonitorSelectorNilUsesHelmValues: false
          storageSpec:
            volumeClaimTemplate:
              spec:
                resources:
                  requests:
                    storage: 10Gi
    mariadb-operator:
      clusterName: cluster.local
      enabled: false
      ha:
        enabled: false
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
      webhook:
        serviceMonitor:
          enabled: false
    minio:
      DeploymentUpdate:
        type: Recreate
      clusterDomain: cluster.local
      enabled: true
      mode: standalone
      persistence:
        size: 20Gi
      replicas: 1
      resources:
        requests:
          memory: 256Mi
    operator:
      image:
        repository: glasskube/operator
        tag: ""
      replicaCount: 1
      resources:
        limits:
          cpu: 1000m
          memory: 640Mi
        requests:
          cpu: 100m
          memory: 400Mi
