---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-release-rancher
  namespace: flux-system
spec:
  chart:
    spec:
      chart: rancher
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rancher
      version: 2.11.2
  interval: 10s
  targetNamespace: rancher-system
  values:
    additionalTrustedCAs: true
    antiAffinity: required
    customLogos:
      accessMode: ReadWriteMany
      enabled: true
      size: 5Gi
      storageClass: longhorn
      volumeKind: persistentVolumeClaim
    ingress:
      servicePort: 443
    livenessProbe:
      failureThreshold: 3
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 10
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 10
    replicas: 3
    resources:
      limits:
        cpu: 2000m
        memory: 4Gi
      requests:
        cpu: 1000m
        memory: 2Gi
    service:
      disableHTTP: true
      type: ClusterIP
    startupProbe:
      failureThreshold: 30
      periodSeconds: 10
      timeoutSeconds: 10
    topologyKey: kubernetes.io/hostname
