---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-release-metrics-server
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metrics-server
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      version: 3.12.2
  interval: 10s
  targetNamespace: metrics-server
  values:
    addonResizer:
      enabled: false
      image:
        repository: registry.k8s.io/autoscaling/addon-resizer
        tag: 1.8.23
      nanny:
        cpu: 0m
        extraCpu: 1m
        extraMemory: 2Mi
        memory: 0Mi
        minClusterSize: 100
        pollPeriod: 300000
        threshold: 5
      resources:
        limits:
          cpu: 40m
          memory: 25Mi
        requests:
          cpu: 40m
          memory: 25Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
    affinity: {}
    apiService:
      annotations: {}
      caBundle: ""
      create: true
      insecureSkipTLSVerify: true
    args: []
    commonLabels: {}
    containerPort: 10250
    defaultArgs:
    - --cert-dir=/tmp
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --kubelet-use-node-status-port
    - --metric-resolution=15s
    deploymentAnnotations: {}
    dnsConfig: {}
    extraVolumeMounts: []
    extraVolumes: []
    fullnameOverride: ""
    hostNetwork:
      enabled: false
    image:
      pullPolicy: IfNotPresent
      repository: registry.k8s.io/metrics-server/metrics-server
      tag: ""
    imagePullSecrets: []
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /livez
        port: https
        scheme: HTTPS
      initialDelaySeconds: 0
      periodSeconds: 10
    metrics:
      enabled: false
    nameOverride: ""
    nodeSelector: {}
    podAnnotations: {}
    podDisruptionBudget:
      enabled: false
      maxUnavailable: null
      minAvailable: null
      unhealthyPodEvictionPolicy: null
    podLabels: {}
    podSecurityContext: {}
    priorityClassName: system-cluster-critical
    rbac:
      create: true
      pspEnabled: false
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /readyz
        port: https
        scheme: HTTPS
      initialDelaySeconds: 20
      periodSeconds: 10
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
    revisionHistoryLimit: null
    schedulerName: ""
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    service:
      annotations: {}
      labels: {}
      port: 443
      type: ClusterIP
    serviceAccount:
      annotations: {}
      create: true
      name: ""
      secrets: []
    serviceMonitor:
      additionalLabels: {}
      enabled: false
      interval: 1m
      metricRelabelings: []
      relabelings: []
      scrapeTimeout: 10s
    tls:
      certManager:
        addInjectorAnnotations: true
        annotations: {}
        duration: ""
        existingIssuer:
          enabled: false
          kind: Issuer
          name: my-issuer
        labels: {}
        renewBefore: ""
      clusterDomain: cluster.local
      existingSecret:
        lookup: true
        name: ""
      helm:
        certDurationDays: 365
        lookup: true
      type: metrics-server
    tmpVolume:
      emptyDir: {}
    tolerations: []
    topologySpreadConstraints: []
    updateStrategy: {}
