---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-release-rancher
  namespace: flux-system
spec:
  chart:
    spec:
      chart: rancher
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rancher
      version: 2.11.2
  interval: 10s
  targetNamespace: rancher-system
  values:
    addLocal: "true"
    additionalTrustedCAs: false
    agentTLSMode: ""
    antiAffinity: required
    auditLog:
      destination: sidecar
      hostPath: /var/log/rancher/audit/
      image:
        pullPolicy: IfNotPresent
        repository: rancher/mirrored-bci-micro
        tag: 15.6.24.2
      level: 1
      maxAge: 7
      maxBackup: 3
      maxSize: 50
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 128Mi
    bootstrapPassword: admin
    customLogos:
      accessMode: ReadWriteOnce
      enabled: true
      size: 20Gi
      storageClass: longhorn
      volumeKind: persistentVolumeClaim
      volumeSubpaths:
        emberUi: ember
        vueUi: vue
    debug: true
    extraObjects: []
    fleet: ""
    hostname: rancher.service.r2b001.site
    imagePullSecrets: []
    ingress:
      enabled: true
      includeDefaultExtraAnnotations: true
      ingressClassName: nginx
      path: /
      pathType: ImplementationSpecific
      servicePort: 80
      tls:
        secretName: tls-rancher-ingress-psdhq
        source: rancher
    letsEncrypt:
      environment: ""
      ingress:
        class: ""
    livenessProbe:
      failureThreshold: 5
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 5
    noProxy: 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local
    postDelete:
      enabled: true
      ignoreTimeoutError: false
      image:
        repository: rancher/shell
        tag: v0.4.1
      namespaceList:
      - cattle-fleet-system
      - cattle-system
      - rancher-operator-system
      timeout: 300
    priorityClassName: rancher-critical
    privateCA: false
    rancherImage: rancher/rancher
    readinessProbe:
      failureThreshold: 6
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
    replicas: 1
    resources:
      limits:
        cpu: 2000m
        memory: 4Gi
      requests:
        cpu: 1000m
        memory: 2Gi
    service:
      annotations: {}
      disableHTTP: false
      type: ClusterIP
    startupProbe:
      failureThreshold: 24
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
    systemDefaultRegistry: ""
    tls: ingress
    topologyKey: topology.kubernetes.io/zone
    useBundledSystemChart: true
    webhook: ""
