---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: odoo
  namespace: flux-system
spec:
  chart:
    spec:
      chart: odoo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 28.2.4
  interval: 10s
  targetNamespace: odoo-system
  values:
    allowEmptyPassword: false
    existingSecret: odoo-secrets
    global:
      compatibility:
        openshift:
          adaptSecurityContext: disabled
      defaultStorageClass: ""
      imagePullSecrets: []
      imageRegistry: ""
      security:
        allowInsecureImages: false
      storageClass: ""
    image:
      pullPolicy: IfNotPresent
      repository: bitnami/odoo
      tag: 18.0.20250405-debian-12-r2
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 50m
      enabled: true
      hostname: odoo.app
      ingressClassName: nginx
      path: /
      secrets:
      - certificate: |
          -----BEGIN CERTIFICATE-----
          ...
          -----END CERTIFICATE-----
        key: |
          -----BEGIN RSA PRIVATE KEY-----
          ...
          -----END RSA PRIVATE KEY-----
        name: odoo-tls
      tls: false
    loadDemoData: false
    odooEmail: admin@example.com
    odooPassword: ""
    persistence:
      enabled: true
      size: 10Gi
      storageClass: longhorn
    postgresql:
      auth:
        database: bitnami_odoo
        existingSecret: odoo-secrets
        existingSecretPasswordKey: postgresql-password
        password: ""
        username: bn_odoo
      enabled: true
      primary:
        persistence:
          size: 5Gi
          storageClass: longhorn
    replicaCount: 1
    resources:
      limits:
        cpu: 2000m
        memory: 2Gi
      requests:
        cpu: 1000m
        memory: 1Gi
