---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: odoo
  namespace: flux-system
spec:
  chart:
    spec:
      chart: odoo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 28.2.4
  interval: 10s
  targetNamespace: odoo-system
  values:
    allowEmptyPassword: false
    existingSecret: odoo-secrets
    image:
      pullPolicy: IfNotPresent
      repository: bitnami/odoo
      tag: 18.0.20250405-debian-12-r2
    loadDemoData: false
    odooEmail: admin@example.com
    odooPassword: ""
    persistence:
      enabled: true
      size: 10Gi
      storageClass: longhorn
    postgresql:
      auth:
        database: bitnami_odoo
        existingSecret: odoo-secrets
        existingSecretPasswordKey: postgresql-password
        password: ""
        username: bn_odoo
      enabled: true
      primary:
        persistence:
          size: 8Gi
          storageClass: longhorn
    replicaCount: 1
    resources:
      limits:
        cpu: 2000m
        memory: 2Gi
      requests:
        cpu: 1000m
        memory: 1Gi
