---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-release-oauth-proxy
  namespace: flux-system
spec:
  chart:
    spec:
      chart: oauth2-proxy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: oauth-proxy
  interval: 10s
  targetNamespace: oauth2-proxy
  values:
    config:
      clientID: a56eace2-cfc4-4d5e-8552-f3edb979ce86
      clientSecret: xxx
      configFile: |-
        provider = "azure"
        azure_tenant="151e41f0-2598-4e00-a9f6-e561efd5c3af"
        provider_display_name = "azure"
        upstreams = [ "file:///dev/null" ]
        cookie_domains = ["137.74.93.227:8091"]
        email_domains= ["*"]
        whitelist_domains = ["137.74.93.227:8091"]
        http_address = "0.0.0.0.4180"
        pass_authorization_header="false"
        set_xauthrequest = "false"
        cookie_secure = "false"
        oidc_issuer_url = "https://login.microsoftonline.com/151e41f0-2598-4e00-a9f6-e561efd5c3af/v2.0"
        redirect_url="https://oauth.service.r2b001.site/oauth2/callback"
        skip_jwt_bearer_tokens = "false"
      cookieSecret: 6EuZQnnaInqwMJG0pn7-xazsOJvRpSkjSIE0wJFB65M=
    ingress:
      annotations: null
      className: nginx
      enabled: true
      hosts:
      - oauth.service.r2b001.site
      path: /
      pathType: ImplementationSpecific
    metrics:
      enabled: true
      port: 44180
    replicaCount: 2
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext:
      capabilities:
        drop:
        - ALL
      enabled: true
      readOnlyRootFilesystem: true
      runAsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000
    service:
      appProtocol: http
      portNumber: 80
      targetPort: 4180
      type: ClusterIP
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
