---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: smartbuilding
  namespace: flux-system
spec:
  interval: 10s
  path: ./manifests/apps/smartbuilding
  prune: true
  sourceRef:
    kind: GitRepository
    name: metalb-git
