---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kustomize-git-metalb
  namespace: flux-system
spec:
  interval: 10s
  path: ./manifests/meta-lb
  prune: true
  sourceRef:
    kind: GitRepository
    name: metalb-git
  targetNamespace: metalb-system
