---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kustomize-git-oauth
  namespace: flux-system
spec:
  interval: 10s
  path: ./manifests/services/oauth2-proxy
  prune: true
  sourceRef:
    kind: GitRepository
    name: metalb-git
  targetNamespace: oauth2-proxy
