---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: smartbuilding-backend
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/bensalah-nabil/Smartbuilding-Backend
