---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: blog-git
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: blog-git
  url: ssh://git@github.com/TUR-PVE/rBlog.git
