---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: opencart
  namespace: flux-system
spec:
  interval: 1m0s
  type: oci
  url: oci://registry-1.docker.io/bitnamicharts/opencart
